In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

#%config InlineBackend.figure_format = 'svg'
#%config InlineBackend.figure_format = 'pdf'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
import kbrgan
import matplotlib
import matplotlib.pyplot as plt
import os
import autograd.numpy as np
import scipy.stats as stats
import torch

## Gaussian kernel

In [3]:
def kgauss(X, Y, sigma2):
    sumx2 = torch.sum(X**2, 1).reshape(-1, 1)
    sumy2 = torch.sum(Y**2, 1).reshape(1, -1)
    D2 = sumx2 - 2.0*X.mm(Y.t()) - sumy2
    K = torch.exp(-D2/(2.0*sigma2))
    return K

In [4]:
n = 7
d = 2
X = torch.randn(n, d)
Y = torch.randn(n, d)
kgauss(X, Y, 1)

tensor([[ 1.0138e+01,  4.4179e-02,  3.4072e+00,  6.7698e-02,  1.8455e+00,
          3.5888e+01,  2.1802e-01],
        [ 6.5412e-01,  4.6887e+00,  9.4396e-02,  1.1851e+00,  8.8664e-01,
          7.4519e-02,  2.2245e-01],
        [ 8.6037e-01,  7.3640e+00,  8.0999e-01,  1.1986e+00,  5.3454e+01,
          4.1499e+00,  1.7516e+00],
        [ 4.6151e-01,  3.1894e+00,  9.6874e-01,  4.6468e-01,  1.2734e+02,
          1.1815e+01,  1.7588e+00],
        [ 4.7365e-01,  2.2173e+00,  1.0929e+00,  3.5145e-01,  1.2997e+02,
          1.6078e+01,  1.6340e+00],
        [ 8.5300e-01,  4.9890e-03,  3.9765e-03,  1.7311e-02,  3.5743e-05,
          4.9937e-04,  4.3193e-04],
        [ 1.3272e+00,  8.0089e+00,  7.1466e-01,  1.6088e+00,  2.2757e+01,
          2.2479e+00,  1.3765e+00]])

## Matrix-vector multiplication

In [19]:
d = 4
x = torch.randn(d)
b = np.random.rand(d)
A = torch.rand(d, d)
A

tensor([[ 0.1738,  0.5911,  0.6960,  0.3612],
        [ 0.0881,  0.8523,  0.8585,  0.2011],
        [ 0.0168,  0.4046,  0.7893,  0.8549],
        [ 0.3636,  0.0293,  0.1978,  0.1228]])

In [20]:
# A*x
A.mv(x)

tensor([ 0.1639, -0.0738,  0.6097,  0.1163])

In [21]:
A.mv(x).dot(x)

tensor(-0.1108)

## Row-wise multiplication

In [22]:
n = 3
A = torch.from_numpy(np.random.randint(0, 5, (n, 2)))
B = torch.from_numpy(np.random.randint(0, 5, (n, 2)))

In [23]:
A

tensor([[ 0,  4],
        [ 2,  4],
        [ 0,  3]])

In [24]:
B

tensor([[ 4,  0],
        [ 2,  3],
        [ 3,  0]])

In [25]:
torch.sum(A*B, 1)

tensor([  0,  16,   0])

In [26]:
tuple(A.shape)

(3, 2)